[package]
name = "dropstf"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
sqlx = { version = "0.5", default_features = false, features = ["macros", "postgres", "json", "runtime-actix-rustls", "offline"] }
dotenv = "0.15"
main_error = "0.1"
tokio = { version = "1", features = ["macros", "time"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
warp = "0.3"
askama = "0.10"
steamid-ng = "1"
steam-resolve-vanity = { version = "0.4", default-features = false, features = ["rustls-tls"] }