[package]
name = "dropstf"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
sqlx = { version = "0.5.11", default_features = false, features = ["macros", "postgres", "json", "runtime-actix-rustls", "offline"] }
dotenv = "0.15.0"
main_error = "0.1.2"
tokio = { version = "1.17.0", features = ["macros", "time"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
warp = "0.3.2"
askama = "0.11.1"
steamid-ng = "1.0.0"
steam-resolve-vanity = { version = "0.4.0", default-features = false, features = ["rustls-tls"] }